import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f4",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#444748",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f0f1f1",
        "outline": "#747878",
        "outline-variant": "#c4c7c7",
        "surface-tint": "#5f5e5e",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "inverse-primary": "#c8c6c5",
        "secondary": "#5d5f5f",
        "on-secondary": "#ffffff",
        "secondary-container": "#dcdddd",
        "on-secondary-container": "#5f6161",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#151c27",
        "on-tertiary-container": "#7d8492",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474646",
        "secondary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#c6c6c7",
        "on-secondary-fixed": "#1a1c1c",
        "on-secondary-fixed-variant": "#454747",
        "tertiary-fixed": "#dce2f3",
        "tertiary-fixed-dim": "#c0c7d6",
        "on-tertiary-fixed": "#151c27",
        "on-tertiary-fixed-variant": "#404754",
        "background": "#f9f9f9",
        "on-background": "#1a1c1c",
        "surface-variant": "#e2e2e2",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        base: "8px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        gutter: "24px",
        "section-gap": "120px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
